-- Sahar schema. Spring Boot runs this automatically at startup (spring.sql.init.mode=always).
--
-- Notes for the curious:
--  * CREATE TABLE IF NOT EXISTS makes this safe to re-run on every boot - on the second start the
--    tables already exist (H2 file mode persists), so nothing is recreated and your edits survive.
--  * GENERATED BY DEFAULT AS IDENTITY is the portable SQL-standard auto-increment. It works the same
--    on H2 (now) and PostgreSQL (step 09), so this one file serves both databases.
--  * Reserved words are avoided on purpose: a column literally called "time" or a table called "week"
--    clashes with SQL keywords on some engines, so we use slot_time, day_of_week, and plural tables.
--  * Times are short strings ("04:37") because that is how the routine is edited and displayed.

CREATE TABLE IF NOT EXISTS app_meta (
    id          INT PRIMARY KEY,
    title       VARCHAR(100) NOT NULL,
    tagline     VARCHAR(200) NOT NULL,
    month_label VARCHAR(60)  NOT NULL
);

CREATE TABLE IF NOT EXISTS prayer_times (
    id          INT PRIMARY KEY,
    fajr        VARCHAR(5) NOT NULL,
    sunrise     VARCHAR(5) NOT NULL,
    dhuhr       VARCHAR(5) NOT NULL,
    asr         VARCHAR(5) NOT NULL,
    maghrib     VARCHAR(5) NOT NULL,
    isha        VARCHAR(5) NOT NULL,
    method_note VARCHAR(500)
);

CREATE TABLE IF NOT EXISTS blocks (
    id    INT PRIMARY KEY,
    label VARCHAR(200)
);

CREATE TABLE IF NOT EXISTS weeks (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    block_id       INT NOT NULL,
    ordinal        INT NOT NULL,
    name           VARCHAR(60)  NOT NULL,
    start_date     VARCHAR(30),
    end_date       VARCHAR(30),
    training_focus VARCHAR(500),
    backend_focus  VARCHAR(500),
    deload         BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS schedule_items (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slot_time  VARCHAR(5)   NOT NULL,
    title      VARCHAR(200) NOT NULL,
    detail     VARCHAR(300),
    category   VARCHAR(20)  NOT NULL,
    day_type   VARCHAR(20)  NOT NULL,
    sort_order INT NOT NULL
);

CREATE TABLE IF NOT EXISTS weekly_grid (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    day_of_week VARCHAR(3)   NOT NULL,
    discipline  VARCHAR(120) NOT NULL,
    note        VARCHAR(200),
    sort_order  INT NOT NULL
);

CREATE TABLE IF NOT EXISTS supplements (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    time_label VARCHAR(60),
    name       VARCHAR(120) NOT NULL,
    dose       VARCHAR(60),
    purpose    VARCHAR(200),
    note       VARCHAR(600),
    sort_order INT NOT NULL
);

CREATE TABLE IF NOT EXISTS diet_sections (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ordinal INT NOT NULL,
    title   VARCHAR(120) NOT NULL,
    body    VARCHAR(800) NOT NULL
);
