-- Flyway migration V3: make the suggested weekly meal plan editable by moving it into a table.
--
-- In the previous version the meal plan was static reference content baked into RoutineSeed. Now it is
-- a real table you can edit through the API/admin (PUT /api/diet-plan/{day}), just like the schedule and
-- the block. Because this is a NEW versioned migration, Flyway applies it once - on a fresh database it
-- runs after V1/V2, and on an existing database (one already at V2) it runs on the next startup and adds
-- the table without touching anything else. That is the whole point of versioned migrations.

CREATE TABLE meal_plan (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    day_of_week VARCHAR(3)   NOT NULL,
    lunch       VARCHAR(200) NOT NULL,
    dinner      VARCHAR(200) NOT NULL,
    note        VARCHAR(160),
    sort_order  INT NOT NULL
);

INSERT INTO meal_plan (day_of_week, lunch, dinner, note, sort_order) VALUES
('Mon', 'Beef/mutton stew (Sun batch) + leafy greens',        'Oily fish — bangda/mackerel',          'Muay Thai · omega-3',                                  0),
('Tue', 'Chicken (batch) + palak / greens',                   'Prawns or white fish',                 'Boxing',                                               1),
('Wed', 'Beef/mutton + heart + greens',                       'Light chicken or surmai',              'Wrestling/BJJ · heart (eat freely)',                   2),
('Thu', 'Chicken + liver (~100g, weekly) + greens',           'Oily fish — rawas',                    'Muay Thai · liver day · omega-3',                      3),
('Fri', 'Mutton/chicken (lighter) + kidney (weekly) + greens','White fish / prawns (light)',          'Padwork taper · kidney day · protect sleep',           4),
('Sat', 'Bigger refeed — beef/mutton + greens (post-spar)',   'Oily fish + extra carbs (recovery)',   'SPAR · hard body, eat well · omega-3',                 5),
('Sun', 'Chicken / leftover stew + palak paneer',             'Fresh fish',                           'Rest · BATCH-COOK red meat + chicken · D3 60K',        6);
