-- Flyway migration V5 (step 23): the training/recovery journal.
--
-- This table is read and written through Spring Data JPA (a Hibernate @Entity + a JpaRepository),
-- whereas every table before it is accessed with hand-written JdbcTemplate SQL. The point of the step is
-- the contrast: same database, two persistence styles, each with its own trade-offs.
--
-- Note that FLYWAY still owns the schema. Hibernate is configured with ddl-auto=validate, so on startup it
-- checks that the JournalEntry entity matches THIS table and refuses to boot if they drift - it never
-- creates or alters tables itself. Versioned migrations stay the single source of truth.
--
-- The identity style (BIGINT GENERATED BY DEFAULT AS IDENTITY) matches the other tables and is portable
-- across H2 and PostgreSQL.

CREATE TABLE journal_entry (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entry_date  DATE NOT NULL,
    energy      INT  NOT NULL,                 -- self-rated 1..5
    note        VARCHAR(1000),
    created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
