-- Flyway migration V1: the schema.
--
-- Flyway runs every db/migration/V<n>__*.sql file once, in version order, and records each in a
-- flyway_schema_history table. Because each migration runs exactly once, we do NOT use
-- "IF NOT EXISTS" here (unlike the old schema.sql, which re-ran on every boot). Flyway's history
-- table is what makes a migration safe to ship to a team and to production.
--
-- This is the same portable DDL that schema.sql had in steps 06-09, so it runs unchanged on H2
-- and on PostgreSQL.

CREATE TABLE app_meta (
    id          INT PRIMARY KEY,
    title       VARCHAR(100) NOT NULL,
    tagline     VARCHAR(200) NOT NULL,
    month_label VARCHAR(60)  NOT NULL
);

CREATE TABLE prayer_times (
    id          INT PRIMARY KEY,
    fajr        VARCHAR(5) NOT NULL,
    sunrise     VARCHAR(5) NOT NULL,
    dhuhr       VARCHAR(5) NOT NULL,
    asr         VARCHAR(5) NOT NULL,
    maghrib     VARCHAR(5) NOT NULL,
    isha        VARCHAR(5) NOT NULL,
    method_note VARCHAR(500)
);

CREATE TABLE blocks (
    id    INT PRIMARY KEY,
    label VARCHAR(200)
);

CREATE TABLE weeks (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    block_id       INT NOT NULL,
    ordinal        INT NOT NULL,
    name           VARCHAR(60)  NOT NULL,
    start_date     VARCHAR(30),
    end_date       VARCHAR(30),
    training_focus VARCHAR(500),
    backend_focus  VARCHAR(500),
    deload         BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE schedule_items (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slot_time  VARCHAR(5)   NOT NULL,
    title      VARCHAR(200) NOT NULL,
    detail     VARCHAR(300),
    category   VARCHAR(20)  NOT NULL,
    day_type   VARCHAR(20)  NOT NULL,
    sort_order INT NOT NULL
);

CREATE TABLE weekly_grid (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    day_of_week VARCHAR(3)   NOT NULL,
    discipline  VARCHAR(120) NOT NULL,
    note        VARCHAR(200),
    sort_order  INT NOT NULL
);

CREATE TABLE supplements (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    time_label VARCHAR(60),
    name       VARCHAR(120) NOT NULL,
    dose       VARCHAR(60),
    purpose    VARCHAR(200),
    note       VARCHAR(600),
    sort_order INT NOT NULL
);

CREATE TABLE diet_sections (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ordinal INT NOT NULL,
    title   VARCHAR(120) NOT NULL,
    body    VARCHAR(800) NOT NULL
);
