package win.l0ve.sahar.repo;

import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.RowMapper;
import org.springframework.jdbc.support.GeneratedKeyHolder;
import org.springframework.jdbc.support.KeyHolder;
import org.springframework.stereotype.Repository;
import win.l0ve.sahar.domain.ScheduleItem;

import java.sql.PreparedStatement;
import java.sql.Statement;
import java.util.List;
import java.util.Optional;

/**
 * Full CRUD over the daily timeline rows.
 *
 * <p>The interesting new piece is {@link #create}: when we INSERT a row whose id is auto-generated by
 * the database, we ask JDBC to hand the new id back via a {@link KeyHolder}. That is why create takes a
 * {@link ScheduleItem} with a {@code null} id and returns one with the id filled in - the client (and the
 * frontend) needs that id to later update or delete the row.
 */
@Repository
public class ScheduleRepository {

    private static final RowMapper<ScheduleItem> MAPPER = (rs, rowNum) -> new ScheduleItem(
            rs.getLong("id"),
            rs.getString("slot_time"),
            rs.getString("title"),
            rs.getString("detail"),
            rs.getString("category"),
            rs.getString("day_type"));

    private final JdbcTemplate jdbc;

    public ScheduleRepository(JdbcTemplate jdbc) {
        this.jdbc = jdbc;
    }

    /** Ordered by time of day - HH:mm strings sort correctly - so new items slot into place. */
    public List<ScheduleItem> findAll() {
        return jdbc.query("SELECT * FROM schedule_items ORDER BY slot_time, id", MAPPER);
    }

    public Optional<ScheduleItem> findById(Long id) {
        return jdbc.query("SELECT * FROM schedule_items WHERE id = ?", MAPPER, id).stream().findFirst();
    }

    public ScheduleItem create(ScheduleItem item) {
        String dayType = item.dayType() == null ? "weekday" : item.dayType();
        KeyHolder keys = new GeneratedKeyHolder();
        jdbc.update(con -> {
            PreparedStatement ps = con.prepareStatement("""
                    INSERT INTO schedule_items (slot_time, title, detail, category, day_type, sort_order)
                    VALUES (?, ?, ?, ?, ?, 0)
                    """, Statement.RETURN_GENERATED_KEYS);
            ps.setString(1, item.time());
            ps.setString(2, item.title());
            ps.setString(3, item.detail());
            ps.setString(4, item.category());
            ps.setString(5, dayType);
            return ps;
        }, keys);
        Long id = keys.getKey().longValue();
        return findById(id).orElseThrow();
    }

    /** Returns the number of rows changed - 0 means "no such id". */
    public int update(Long id, ScheduleItem item) {
        String dayType = item.dayType() == null ? "weekday" : item.dayType();
        return jdbc.update("""
                UPDATE schedule_items
                   SET slot_time = ?, title = ?, detail = ?, category = ?, day_type = ?
                 WHERE id = ?
                """,
                item.time(), item.title(), item.detail(), item.category(), dayType, id);
    }

    /** Returns the number of rows deleted - 0 means "no such id". */
    public int delete(Long id) {
        return jdbc.update("DELETE FROM schedule_items WHERE id = ?", id);
    }

    /** Seed all rows on a fresh database (ids are auto-assigned). */
    public void insertAll(List<ScheduleItem> items) {
        int order = 0;
        for (ScheduleItem it : items) {
            jdbc.update("""
                    INSERT INTO schedule_items (slot_time, title, detail, category, day_type, sort_order)
                    VALUES (?, ?, ?, ?, ?, ?)
                    """,
                    it.time(), it.title(), it.detail(), it.category(), it.dayType(), order++);
        }
    }
}
