package com.ramishtaha.sahar.journal;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import org.hibernate.annotations.CreationTimestamp;

import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 * A single journal entry, persisted by Spring Data JPA / Hibernate (step 23).
 *
 * <p>Notice how different this is from the domain {@code record}s used everywhere else (e.g. {@code PrayerTimes}):
 * a JPA {@code @Entity} must be a mutable class with a no-arg constructor, because Hibernate instantiates it
 * reflectively and populates the fields when reading a row. That is the cost of the convenience JPA gives you
 * elsewhere (you write no SQL for CRUD). The records suit the JdbcTemplate side, where WE map rows by hand and
 * value immutability; the entity suits the JPA side. Same app, two honest styles.
 *
 * <ul>
 *   <li>{@code @Id} + {@code @GeneratedValue(IDENTITY)} maps to the {@code BIGINT GENERATED BY DEFAULT AS
 *       IDENTITY} column - the database assigns the id on insert.</li>
 *   <li>{@code @CreationTimestamp} lets Hibernate stamp {@code created_at} on first save, so we never set it
 *       by hand.</li>
 * </ul>
 */
@Entity
@Table(name = "journal_entry")
public class JournalEntry {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "entry_date", nullable = false)
    private LocalDate entryDate;

    @Column(nullable = false)
    private int energy;

    @Column(length = 1000)
    private String note;

    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /** Required by JPA. Not for application use. */
    protected JournalEntry() {
    }

    public JournalEntry(LocalDate entryDate, int energy, String note) {
        this.entryDate = entryDate;
        this.energy = energy;
        this.note = note;
    }

    public Long getId() {
        return id;
    }

    public LocalDate getEntryDate() {
        return entryDate;
    }

    public int getEnergy() {
        return energy;
    }

    public String getNote() {
        return note;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }
}
